export const TOGGLE_CART_DRAWER = 'TOGGLE_CART_DRAWER';
export const TOGGLE_MENU_DRAWER = 'TOGGLE_MENU_DRAWER';
export const START_PRODUCTS_FETCH_LOADING = 'START_PRODUCTS_FETCH_LOADING';
export const STOP_PRODUCTS_FETCH_LOADING = 'STOP_PRODUCTS_FETCH_LOADING';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
