export const TOGGLE_CART_DRAWER = 'TOGGLE_CART_DRAWER';
export const TOGGLE_MENU_DRAWER = 'TOGGLE_MENU_DRAWER';
export const START_PRODUCTS_FETCH_LOADING = 'START_PRODUCTS_FETCH_LOADING';
export const STOP_PRODUCTS_FETCH_LOADING = 'STOP_PRODUCTS_FETCH_LOADING';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
export const UPDATE_CART_LIST = 'UPDATE_CART_LIST';
export const ADD_TO_CART_LIST = 'ADD_TO_CART_LIST';
export const REMOVE_TO_CART_LIST = 'REMOVE_TO_CART_LIST';
export const UPDATE_CART_LIST_QTY = 'UPDATE_CART_LIST_QTY';
export const SYNC_CART_LIST_FROM_LOCAL_STORAGE =
  'SYNC_CART_LIST_FROM_LOCAL_STORAGE';
